=== BackupTheBerlios/xmlinterface/xmlinterface/project/xsd/stylesSchema.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" version="1.0">
	<xsd:element name="xmlgui-styles">
		<xsd:annotation>
			<xsd:documentation>Comment describing your root element</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="widget-styles" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:complexContent>
							<xsd:extension base="widget-styles"/>
						</xsd:complexContent>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="widget-styles">
		<xsd:sequence>
			<xsd:element name="uiType" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:complexContent>
						<xsd:extension base="uiType"/>
					</xsd:complexContent>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="uiType">
		<xsd:sequence>
			<xsd:element name="foreground" minOccurs="0">
				<xsd:complexType>
					<xsd:complexContent>
						<xsd:extension base="foreground"/>
					</xsd:complexContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="background" minOccurs="0">
				<xsd:complexType>
					<xsd:complexContent>
						<xsd:extension base="background"/>
					</xsd:complexContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="font" minOccurs="0">
				<xsd:complexType>
					<xsd:complexContent>
						<xsd:extension base="font"/>
					</xsd:complexContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="width" minOccurs="0">
				<xsd:complexType>
					<xsd:complexContent>
						<xsd:extension base="width"/>
					</xsd:complexContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="height" minOccurs="0">
				<xsd:complexType>
					<xsd:complexContent>
						<xsd:extension base="height"/>
					</xsd:complexContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="border" minOccurs="0">
				<xsd:complexType>
					<xsd:complexContent>
						<xsd:extension base="border"/>
					</xsd:complexContent>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="type" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="foreground">
		<xsd:sequence>
			<xsd:element name="color" minOccurs="1" maxOccurs="1">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="color"/>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="background">
		<xsd:sequence>
			<xsd:element name="color">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="color"/>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="font">
		<xsd:sequence>
			<xsd:element name="color">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="color"/>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="width">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="width"/>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="height">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="height"/>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="type">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="type"/>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="border">
		<xsd:sequence>
			<xsd:element name="color">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="color"/>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="width">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="width"/>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="type">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="type"/>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="color">
		<xsd:simpleContent>
			<xsd:extension base="__color"/>
		</xsd:simpleContent>
	</xsd:complexType>
	<xsd:complexType name="width">
		<xsd:simpleContent>
			<xsd:extension base="__width"/>
		</xsd:simpleContent>
	</xsd:complexType>
	<xsd:complexType name="height">
		<xsd:simpleContent>
			<xsd:extension base="__height"/>
		</xsd:simpleContent>
	</xsd:complexType>
	<xsd:complexType name="type">
		<xsd:simpleContent>
			<xsd:extension base="__type"/>
		</xsd:simpleContent>
	</xsd:complexType>
	<xsd:simpleType name="__color">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="red">
				<xsd:annotation>
					<xsd:documentation xml:lang="en">RED COLOR</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="blue">
				<xsd:annotation>
					<xsd:documentation xml:lang="en">BLUE COLOR</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="green">
				<xsd:annotation>
					<xsd:documentation xml:lang="en">GREEN COLOR</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="yellow">
				<xsd:annotation>
					<xsd:documentation xml:lang="en">YELLOW COLOR</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="black">
				<xsd:annotation>
					<xsd:documentation xml:lang="en">BLACK COLOR</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="white">
				<xsd:annotation>
					<xsd:documentation xml:lang="en">WHITE COLOR</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="__width">
		<xsd:restriction base="xsd:int">
			<xsd:minLength value="1"/>
			<xsd:maxLength value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="__height">
		<xsd:restriction base="xsd:int">
			<xsd:minLength value="1"/>
			<xsd:maxLength value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="__type">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="255"/>
			<xsd:whiteSpace value="preserve"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== BackupTheBerlios/xmlinterface/xmlinterface/gerald/vstdom/xml/styles.xml
<?xml version="1.0" encoding="UTF-8"?><xmlgui-styles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:\Uni\Projektarbeit\Projekt_20.04.04\stylesSchema.xsd">	<widget-styles>		<uiType name="default" type="button">					<foreground>				<color>red</color>			</foreground>			<background>				<color>green</color>			</background>			<font>				<color>black</color>				<width>1</width>				<height>1000</height>				<type></type>			</font>			<border>				<color>yellow</color>							<width>10000</width>				<type/>			</border>		</uiType>	</widget-styles></xmlgui-styles>

=== BackupTheBerlios/xmlinterface/xmlinterface/project/xml/styles.xml
<?xml version="1.0" encoding="UTF-8"?><xmlgui-styles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:\Uni\Projektarbeit\Projekt_20.04.04\stylesSchema.xsd">	<widget-styles>		<!-- default layout for Buttons -->		<uiType id="defaultButton" type="button">			<background>				<color>grey</color>			</background>			<font>				<color>black</color>				<size>10</size>				<type>Times New Roman</type>			</font>		</uiType>		<!-- default layout for Textfields-->		<uiType id="defaultTextfield" type="textfield">			<background>				<color>white</color>			</background>			<font>				<color>black</color>				<size>10</size>				<type>Times New Roman</type>			</font>			<border>				<color>black</color>				<width>1</width>				<!-- durchgezogene Linie -->				<borderType>line</borderType>			</border>		</uiType>		<!-- default layout for MenuItems-->		<uiType id="defaultMenuItem" type="menuitem">			<background>				<color>grey</color>			</background>			<font>				<color>black</color>				<size>10</size>				<type>Times New Roman</type>			</font>		</uiType>		<!-- default layout for Checkboxes -->		<uiType id="defaultCheckbox" type="checkbox">			<background>				<color>white</color>			</background>			<font>				<color>black</color>				<size>10</size>				<type>Times New Roman</type>			</font>		</uiType>		<!-- default layout for Comboboxes -->		<uiType id="defaultCombobox" type="combobox">			<background>				<color>white</color>			</background>			<font>				<color>black</color>				<size>10</size>				<type>Times New Roman</type>			</font>		</uiType>	</widget-styles></xmlgui-styles>
