=== BackupTheBerlios/xmlinterface/xmlinterface/project/xsd/xmlInterface_2.xsd
<?xml version="1.0" encoding="ISO-8859-1"?><xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" version="1.0">	<xsd:element name="xmlgui">		<xsd:annotation>			<xsd:documentation>Comment describing your root element</xsd:documentation>		</xsd:annotation>		<xsd:complexType>			<xsd:sequence>				<xsd:element name="widgets" maxOccurs="unbounded">					<xsd:complexType>						<xsd:complexContent>							<xsd:extension base="widgets"/>						</xsd:complexContent>					</xsd:complexType>				</xsd:element>			</xsd:sequence>		</xsd:complexType>	</xsd:element>	<xsd:complexType name="widgets">		<xsd:sequence>			<xsd:element name="widget" maxOccurs="unbounded">				<xsd:complexType>					<xsd:complexContent>						<xsd:extension base="widget"/>					</xsd:complexContent>				</xsd:complexType>			</xsd:element>		</xsd:sequence>	</xsd:complexType>	<xsd:complexType name="widget">		<xsd:sequence>			<xsd:element name="properties" minOccurs="0">				<xsd:complexType>					<xsd:complexContent>						<xsd:extension base="properties"/>					</xsd:complexContent>				</xsd:complexType>			</xsd:element>			<xsd:element name="events" minOccurs="0">				<xsd:complexType>					<xsd:complexContent>						<xsd:extension base="events"/>					</xsd:complexContent>				</xsd:complexType>			</xsd:element>			<xsd:element name="widgets" minOccurs="0">				<xsd:complexType>					<xsd:complexContent>						<xsd:extension base="widgets"/>					</xsd:complexContent>				</xsd:complexType>			</xsd:element>		</xsd:sequence>		<xsd:attribute name="name" type="xsd:string" use="required"/>		<xsd:attribute name="type" type="xsd:string" use="required"/>		<xsd:attribute name="uiType" type="xsd:string" use="optional"/>	</xsd:complexType>	<xsd:complexType name="properties">		<xsd:sequence>			<xsd:element name="property" maxOccurs="unbounded">				<xsd:complexType>					<xsd:simpleContent>						<xsd:extension base="property"/>					</xsd:simpleContent>				</xsd:complexType>			</xsd:element>		</xsd:sequence>	</xsd:complexType>	<xsd:complexType name="events">		<xsd:sequence>			<xsd:element name="event" maxOccurs="unbounded">				<xsd:complexType>					<xsd:simpleContent>						<xsd:extension base="event"/>					</xsd:simpleContent>				</xsd:complexType>			</xsd:element>		</xsd:sequence>	</xsd:complexType>	<xsd:complexType name="property">		<xsd:simpleContent>			<xsd:extension base="__property">				<xsd:attribute name="name" type="xsd:string" use="required"/>			</xsd:extension>		</xsd:simpleContent>	</xsd:complexType>	<xsd:complexType name="event">		<xsd:simpleContent>			<xsd:extension base="__event">				<xsd:attribute name="name" type="xsd:string" use="required"/>				<xsd:attribute name="type" type="xsd:string" use="required"/>				<xsd:attribute name="uiType" type="xsd:string" use="optional"/>			</xsd:extension>		</xsd:simpleContent>	</xsd:complexType>	<xsd:simpleType name="__property">		<xsd:restriction base="xsd:string">			<xsd:minLength value="1"/>			<xsd:maxLength value="255"/>			<xsd:whiteSpace value="preserve"/>		</xsd:restriction>	</xsd:simpleType>	<xsd:simpleType name="__event">		<xsd:restriction base="xsd:string">			<xsd:minLength value="0"/>			<xsd:maxLength value="255"/>			<xsd:whiteSpace value="preserve"/>		</xsd:restriction>	</xsd:simpleType></xsd:schema>

=== BackupTheBerlios/xmlinterface/xmlinterface/project/xml/beispiel_2.xml
<?xml version="1.0" encoding="UTF-8"?><xmlgui xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:\Uni\Projektarbeit\Projekt_20.04.04\xmlInterface_2.xsd">	<widgets>		<!-- widget - window komponente allgemein		uiType - WidgetStyle -->		<widget name="Fenster" type="window" uiType="">			<!-- properties beschreiben widget -->			<properties>				<property name="width">100</property>				<property name="height">100</property>				<property name="xCoord">0</property>				<property name="yCoord">0</property>				<property name="title">FensterTitel</property>			</properties>			<!-- besonderes event ausloesen -->			<events>				<event name="close" type="closeEvent"/>				<event name="minimize" type="minimizeEvent"/>				<event name="maximize" type="maximizeEvent"/>			</events>			<widgets>				<widget name="MenuBar" type="menuBar">					<widgets>						<widget name="FileMenu" type="Menu">							<properties>								<property name="text">File</property>								<!-- menueintrag file reagiert auf Alt+F -->								<property name="mnemonic">Alt+F</property>							</properties>							<widgets>								<widget name="open" type="MenuItem">									<properties>										<property name="text">Oeffnen...</property>									</properties>									<events>										<event name="openPressed" type="mouseEvent">leftClick</event>									</events>								</widget>								<widget name="ende" type="MenuItem">									<properties>										<property name="text">Exit...</property>									</properties>								</widget>							</widgets>						</widget>					</widgets>				</widget>				<widget name="Knopf" type="button" uiType="">					<properties>						<property name="width">10</property>						<property name="height">10</property>						<property name="xCoord">0</property>						<property name="yCoord">0</property>						<property name="text">ButtonText</property>					</properties>					<events>						<!-- mPressed - name der fkt. mit eventinhalt aus dem eigenen srcCode						event wird an die globale CallBackMethod uebermittelt und dann an mPressed weiter deligiert -->						<event name="mPressed" type="mousePressEvent">leftClick</event>					</events>				</widget>				<widget name="" type="textfield">					<properties>						<property name="width">10</property>						<property name="height">10</property>						<property name="xCoord">0</property>						<property name="yCoord">0</property>						<property name="text">Initialisierungstext des Textfeldes</property>					</properties>					<events>						<!-- einfacher Undo/Redo-Manager -->						<event name="undoPressed" type="keyPressEvent">Ctrl+Z</event>						<event name="redoPressed" type="keyPressEvent">Ctrl+Y</event>					</events>				</widget>				<widget name="" type="combobox">					<properties>						<property name="width">10</property>						<property name="height">10</property>						<property name="xCoord">0</property>						<property name="yCoord">0</property>						<property name="text">ButtonText</property>					</properties>					<events>						<!-- mPressed - name der fkt. mit eventinhalt eigener srcCode -->						<event name="mPressed" type="mousePressEvent" uiType=""/>					</events>					<widgets>						<widget name="element1" type="comboboxElement">							<properties>								<property name="text">Element1</property>							</properties>						</widget>						<widget name="element2" type="button">							<properties>								<property name="text">Element2</property>							</properties>						</widget>					</widgets>				</widget>				<widget name="" type="checkox">					<properties>						<property name="width">10</property>						<property name="height">10</property>						<property name="xCoord">0</property>						<property name="yCoord">0</property>						<property name="text">ChecBoxText</property>						<!-- checked vom type boolean -->						<property name="checked">false</property>					</properties>					<events>						<!-- mPressed - name der fkt. mit eventinhalt eigener srcCode -->						<event name="mPressed" type="mousePressEvent" uiType=""/>					</events>				</widget>			</widgets>		</widget>	</widgets></xmlgui>
